# Generated by Django 4.0.2 on 2024-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Аббревиатура')),
                ('short_name', models.CharField(max_length=100, verbose_name='Наименование краткое')),
                ('full_name', models.CharField(max_length=255, verbose_name='Наименование полное')),
                ('internal_code', models.CharField(max_length=100, verbose_name='Код внутренний')),
                ('cipher', models.CharField(max_length=100, verbose_name='Шифр')),
                ('ekps_code', models.CharField(max_length=100, verbose_name='Код ЕКПС')),
                ('kvt_code', models.CharField(max_length=100, verbose_name='Код КВТ')),
                ('drawing_number', models.CharField(max_length=100, verbose_name='Чертёжный номер')),
                ('nomenclature_type', models.CharField(max_length=100, verbose_name='Вид номенклатуры')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
